name: 'rinha-de-backend-3'

#  1.5 CPUs = 0.5 PostgreSQL + 2 x 0.45 Spring Boot + 0.1 NGinx
#   350  MB =  50 PostgreSQL + 2 x  145 Spring Boot +  10 NGinx

services:

# rinha redis
  javinha-redis:
    image: redis:7.2
    container_name: javinha-redis
    hostname: javinha-redis
#    environment:
#      - REDIS_PASSWORD=rinha
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "70MB"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "rinha", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  redis-data:

# rinha database
#  javinha-db:
#    image: postgres:latest
#    container_name: javinha-db
#    hostname: javinha-db
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=rinha
#      - POSTGRES_DB=rinha2025
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./init-db-rinha.sql:/docker-entrypoint-initdb.d/init.sql:ro
#    command: postgres -c checkpoint_timeout=600 -c max_wal_size=2096 -c synchronous_commit=0 -c full_page_writes=0 -c fsync=off -c check_function_bodies=false
#    deploy:
#      resources:
#        limits:
#          cpus: "0.50"
#          memory: "70MB"
#    ulimits:
#      nofile:
#        soft: 1000000
#        hard: 1000000
#    healthcheck:
#      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d rinha2025'"]
#      interval: 5s
#      timeout: 5s
#      retries: 20
#      start_period: 10s

