spring:
  application:
   name: player456
#  datasource:
#   url: ${DB_URL:jdbc:postgresql://localhost:5432/rinha2025}
#   username: admin
#   password: rinha
#   driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_SERVER:localhost}
      password: ${REDIS_PASSWORD:rinha}
      port: ${REDIS_PORT:6379}
      database: 0
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    locale: en_US
  serialization:
    write-dates-as-timestamps: false
  threads:
    virtual:
      enabled: true

payment:
  default: ${PAYMENT_DEFAULT_SERVER:http://localhost:8001}
  fallback: ${PAYMENT_FALLBACK_SERVER:http://localhost:8002}
  enableScheduling: ${ENABLE_SCHEDULING:false}

server:
  port: ${SERVER_PORT:9999}
  tomcat:
    threads:
      max: 20
      min-spare: 5
    connection-timeout: 10000
    max-connections: 200
    accept-count: 10
