spring:
  application:
   name: player456
#  datasource:
#   url: ${DB_URL:jdbc:postgresql://localhost:5432/rinha2025}
#   username: admin
#   password: rinha
#   driver-class-name: org.postgresql.Driver
#  data:
#    redis:
#      host: ${REDIS_SERVER:localhost}
#      password: ${REDIS_PASSWORD:rinha}
#      port: ${REDIS_PORT:6379}
#      database: 0
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    locale: en_US
  redis:
    lettuce:
      pool:
       enabled: true
       max-active: 3
       max-idle: 1
       min-idle: 0
    timeout: 50ms
  serialization:
    write-dates-as-timestamps: false
  threads:
    virtual:
      enabled: false

payment:
  default: ${PAYMENT_DEFAULT_SERVER:http://localhost:8001}
  fallback: ${PAYMENT_FALLBACK_SERVER:http://localhost:8002}
  enableScheduling: ${ENABLE_SCHEDULING:false}

redis:
  host: ${REDIS_SERVER:localhost}
  port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:9999}
  tomcat:
    threads:
      max: 50
      min-spare: 5
    connection-timeout: 10000
    max-connections: 500
    accept-count: 20
